import random

from datetime import datetime


class BFAttack:
    def __init__(self):
        self.attacker_subnet = None
        self.attacker_ips = []
        self.defenses_applied = []
        self.attack_active = True
        self.rate_limited = False

        # Usernames generated by claude
        self.user_ip_map = {
            "jsmith": self.generate_random_ip(),
            "mwilson": self.generate_random_ip(),
            "tlee": self.generate_random_ip(),
            "rgarcia": self.generate_random_ip(),
            "bknight": self.generate_random_ip(),
            "alopez": self.generate_random_ip(),
            "dchen": self.generate_random_ip(),
            "kpatel": self.generate_random_ip(),
            "mthompson": self.generate_random_ip(),
            "sjohnson": self.generate_random_ip(),
            "rwilliams": self.generate_random_ip(),
            "tnguyen": self.generate_random_ip(),
            "lmartinez": self.generate_random_ip(),
            "banders": self.generate_random_ip(),
            "cwhite": self.generate_random_ip(),
        }

    # Usernames generated by claude
    real_usernames = [
        "jsmith",
        "mwilson",
        "tlee",
        "rgarcia",
        "bknight",
        "alopez",
        "dchen",
        "kpatel",
        "mthompson",
        "sjohnson",
        "rwilliams",
        "tnguyen",
        "lmartinez",
        "banders",
        "cwhite",
    ]

    # Google: How do I genearte a random IP address in python
    # Generates a random ip for the attacker to be assigned
    def generate_attacker_ip(self):
        # Generate a subnet so multiple IPs come from same range
        self.attacker_subnet = f"{random.randint(1, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}"
        self.defenses_applied = []
        self.attacker_ips = [
            f"{self.attacker_subnet}.{i}" for i in random.sample(range(1, 255), 5)
        ]
        self.attack_active = True
        self.rate_limited = False
        return self.attacker_subnet  # return subnet so frontend knows what to block

    # Claude: How does ufw limit ssh work in the real world?
    def ufw_limit_ssh(self):
        self.defenses_applied.append("ufw_limit_ssh")
        return "Rule added: Limit ssh\nSSH connections are now limited to 6 per 30 seconds."

    def ufw_deny(self, ip: str):
        if self.check_ip(ip):
            self.defenses_applied.append("ufw_deny_")
            self.attack_active = False
            return f"Rule added: deny from {ip}\nAttack successfully blocked!"
        else:
            self.defenses_applied.append("ufw_deny_wrong_ip")
            return f"Rule added: deny from {ip}\nRule applied but the attack continues."

    # Claude: How does netstat command look like in logs?

    def netstat(self):
        lines = []
        connections = []
        self.defenses_applied.append("netstat")

        # Add attacker connections
        for ip in self.attacker_ips:
            port = random.randint(10000, 65535)
            connections.append(f"{'tcp':<6} {f'{ip}:{port}':<25} {'SYN_RECV':<15}")

        for user, ip in list(self.user_ip_map.items())[:5]:
            port = random.randint(10000, 65535)
            connections.append(f"{'tcp':<6} {f'{ip}:{port}':<25} {'ESTABLISHED':<15}")

        # Shuffle so attackers aren't all at the top
        random.shuffle(connections)

        lines.append("Active Internet connections")
        lines.append(f"{'Proto':<6} {'Foreign Address':<25} {'State':<15}")
        lines.append("-" * 50)
        lines.extend(connections)

        return "\n".join(lines)

    # Generates a random ip for fake users
    def generate_random_ip(self):
        return f"{random.randint(1, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}"

    # Accepts user input ip and checks to see if it is the attackers ip
    def check_ip(self, ip: str):
        # User should block the subnet e.g. "209.132.191.0/24"
        return self.attacker_subnet in ip

    # Generated fake username and noise using claude
    attack_usernames = [
        "root",
        "admin",
        "ubuntu",
        "deploy",
        "test",
        "pi",
        "oracle",
        "guest",
    ]

    # Generated by chatgpt
    noise_types = ["cron", "sudo", "systemd"]

    # Generates random logs to make it a real world situation
    def generate_logs(self):
        timestamp = datetime.now().strftime("%b %d %H:%M:%S")
        pid = random.randint(10000, 99999)
        port = random.randint(10000, 65535)

        if not self.attack_active:
            test = random.randint(1, 3)
        elif self.rate_limited:
            test = random.randint(1, 10)
        else:
            test = random.randint(1, 8)

        # Asked for an example of noise and attacks from claude
        if test == 1:
            user = random.choice(self.real_usernames)
            return f"{timestamp} webserver01 sshd[{pid}]: Accepted password for {user} from {self.user_ip_map[user]} port {port} ssh2"
        elif test == 2:
            user = random.choice(self.real_usernames)
            return f"{timestamp} webserver01 sshd[{pid}]: Failed password for {user} from {self.user_ip_map[user]} port {port} ssh2"
        elif test == 3:
            user = random.choice(self.real_usernames)
            return f"{timestamp} webserver01 CRON[{pid}]: pam_unix(cron:session): session opened for user {user}"
        elif test == 4:
            user = random.choice(self.real_usernames)
            return f"{timestamp} webserver01 sshd[{pid}]: Disconnected from user {user} {self.user_ip_map[user]} port {port}"
        elif test == 5:
            user = random.choice(self.real_usernames)
            return f"{timestamp} webserver01 systemd[{pid}]: Started Session of user {user}"
        else:
            attacker_ip = random.choice(self.attacker_ips)
            username = random.choice(self.attack_usernames)
            return f"{timestamp} webserver01 sshd{pid}: Failed password for invalid user {username} from {attacker_ip} port {port} ssh2"
